version: '3'
services:
  go:
    build: ./go
    volumes:
      - ./go:/go/src/work
    tty: true

  firebase:
    build: ./firebase
    volumes:
      - ./firebase:/opt/pattern_recognition/firebase
      - ./go/wasm:/opt/pattern_recognition/firebase/public/wasm
    ports:
      - 4000:4000  # Emulator Suite UI
      - 5000:5000  # Firebase Hosting
      - 5001:5001  # Clound Functions
      - 9000:9000  # Realtime Database
      - 8080:8080  # Cloud Firestore
      - 8085:8085  # Cloud Pub/Sub
    tty: true
